name: MiningOffhands
main: me.harry.miningoffhands.MiningOffhands
author: harry8668
version: 1.1
api-version: 1.20
commands:
  setoffhandmulti:
    description: set you're held item to have <amount> drops in offhand